name: CD - Gerar Artefato

on:
  workflow_run:
    workflows: ["CI - Java Cartas System"]
    types:
      - completed

jobs:
  delivery:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: javac $(find . -name "*.java")

      - name: Gerar arquivo .jar
        run: jar cfe cartas-app.jar Main $(find . -name "*.class")

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cartas-app
          path: cartas-app.jar

      - name: Finalização
        run: echo "Entrega concluída com sucesso."
